package uk.gov.hmcts.cp.informantregister.pipeline;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import uk.gov.hmcts.cp.informantregister.config.JacksonConfig;
import uk.gov.hmcts.cp.informantregister.domain.RegisterFragment;
import uk.gov.hmcts.cp.informantregister.support.JsonParity;

/**
 * The JUnit twins of the legacy {@code SetInformantRegister} Jest suite.
 *
 * <p>One twin per Jest case, in the order the legacy file declares them: nineteen cases across four
 * describes. Each runs the ported {@link RegisterBuilder} over the same input the Jest case uses and
 * compares the whole fragment tree against a golden captured from the legacy function app itself.
 *
 * <p><strong>Why goldens rather than transcribed assertions.</strong> The Jest cases assert inline
 * and shallowly — a length here, a date there — so transcribing them would inherit their blind spots
 * and prove almost nothing about the tree beneath. The design calls for capturing actual legacy
 * output instead, so every field of every result of every defendant is pinned, not just the handful
 * the original author happened to check. The goldens were produced by running the real legacy handler
 * (see the provenance note below), and the assertions the Jest suite does make were verified against
 * them.
 *
 * <p><strong>Provenance of the goldens.</strong> Generated by invoking
 * {@code SetInformantRegister/index.js} directly, once per case, each with a fresh module registry so
 * no case inherits another's mutations — the legacy filter rewrites the hearing payload in place.
 * Twelve of the nineteen Jest cases pass no shared time, and the legacy stamps those with the wall
 * clock, so the generator froze the clock at {@code 2021-06-15T09:30:00Z}; these twins inject the same
 * instant. That instant is deliberately inside British Summer Time, so the goldens also pin the
 * legacy's habit of labelling a London wall-clock time with a literal {@code Z}.
 *
 * <p><strong>Fixtures are byte-identical copies</strong> of the seven JSON files under
 * {@code SetInformantRegister/test/}, verified with {@code diff} at copy time, as constitution
 * Principle I requires.
 */
@DisplayName("RegisterBuilder — parity with the legacy SetInformantRegister")
class RegisterBuilderParityTest {

    /** The instant the goldens were captured at, for the cases that carry no shared time. */
    private static final Clock FROZEN =
            Clock.fixed(Instant.parse("2021-06-15T09:30:00Z"), ZoneOffset.UTC);

    private static final String FIXTURES = "/fixtures/setinformantregister/";

    private final ObjectMapper mapper = JacksonConfig.contractObjectMapper();

    private final RegisterBuilder builder = new RegisterBuilder(new HearingDates(FROZEN));

    @Nested
    @DisplayName("Set Informant Register from prosecution case")
    class FromProsecutionCase {

        @Test
        @DisplayName("should return the correct Informant register fragment from prosecution case")
        void should_return_the_correct_fragment_from_a_prosecution_case() {
            assertParity(
                    "case-01-correct-fragment-from-prosecution-case",
                    fixture("hearing-results-from-prosecution-case.json"),
                    "2020-06-01T10:00:00Z");
        }

        @Test
        @DisplayName("should filter by unique prosecutionAuthId")
        void should_filter_by_unique_prosecution_authority() {
            assertParity(
                    "case-02-filter-by-unique-authority",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"),
                            prosecutionCase("prosecution-auth-id-2", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter by unique prosecutionAuthId but not master defendant id")
        void should_filter_by_unique_authority_but_not_master_defendant() {
            assertParity(
                    "case-03-unique-authority-not-master-defendant",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"),
                            prosecutionCase("prosecution-auth-id-2", "master-defendant-id-1"))),
                    null);
        }

        @Test
        @DisplayName("should group informant register fragments by prosecutionAuthId across cases")
        void should_group_fragments_by_authority_across_cases() {
            assertParity(
                    "case-04-group-by-authority-across-cases",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"),
                            prosecutionCase("prosecution-auth-id-1", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter by prosecution authority id and then by master defendant id")
        void should_filter_by_authority_then_by_master_defendant() {
            assertParity(
                    "case-05-filter-by-authority-then-master-defendant",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"),
                            prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"))),
                    null);
        }

        @Test
        @DisplayName("should carry the groupId of a group-master prosecution case")
        void should_carry_the_group_id_of_a_group_master_case() {
            assertParity(
                    "case-06-group-master-case-group-id",
                    fixture("group-master-case.json"),
                    "2021-09-27T13:02:32.591Z");
        }
    }

    @Nested
    @DisplayName("Set Informant Register from court application")
    class FromCourtApplication {

        @Test
        @DisplayName("should return the correct Informant register fragment from court application")
        void should_return_the_correct_fragment_from_a_court_application() {
            assertParity(
                    "case-07-correct-fragment-from-court-application",
                    fixture("hearing-results-from-court-application.json"),
                    "2021-03-11T22:18:24.506Z");
        }

        @Test
        @DisplayName("should not return a fragment when there is no masterdefendant for subject")
        void should_not_return_a_fragment_without_a_subject_master_defendant() {
            assertParity(
                    "case-08-application-without-master-defendant",
                    fixture("hearing-results-from-court-application-without-masterdefendant.json"),
                    "2021-03-11T22:18:24.506Z");
        }

        @Test
        @DisplayName("should not return a fragment when applicant is masterDefendant")
        void should_not_return_a_fragment_when_the_applicant_is_the_master_defendant() {
            assertParity(
                    "case-09-applicant-is-master-defendant",
                    fixture(
                        "hearing-results-from-court-application-applicant-masterDefendant.json"),
                    "2021-03-11T22:18:24.506Z");
        }

        @Test
        @DisplayName("should filter unique prosecutionAuthId")
        void should_filter_unique_authority_across_applications() {
            assertParity(
                    "case-10-application-filter-unique-authority",
                    hearing(applications(
                            application("prosecution-auth-id-1", "master-defendant-id-1"),
                            application("prosecution-auth-id-2", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter unique prosecutionAuthId but not master defendant id")
        void should_filter_unique_authority_but_not_master_defendant_across_applications() {
            assertParity(
                    "case-11-application-unique-authority-not-master-defendant",
                    hearing(applications(
                            application("prosecution-auth-id-1", "master-defendant-id-1"),
                            application("prosecution-auth-id-2", "master-defendant-id-1"))),
                    null);
        }

        @Test
        @DisplayName("should group fragments by prosecutionAuthId across the applications")
        void should_group_fragments_by_authority_across_applications() {
            assertParity(
                    "case-12-application-group-by-authority",
                    hearing(applications(
                            application("prosecution-auth-id-1", "master-defendant-id-1"),
                            application("prosecution-auth-id-1", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter by prosecution authority id and then by master defendant id")
        void should_filter_by_authority_then_master_defendant_across_applications() {
            assertParity(
                    "case-13-application-filter-authority-then-master-defendant",
                    hearing(applications(
                            application("prosecution-auth-id-1", "master-defendant-id-1"),
                            application("prosecution-auth-id-1", "master-defendant-id-1"))),
                    null);
        }
    }

    @Nested
    @DisplayName("Set Informant Register from both prosecution case and court application")
    class FromCaseAndApplication {

        @Test
        @DisplayName("should return the correct fragment from both case and court application")
        void should_return_the_correct_fragment_from_case_and_application() {
            assertParity(
                    "case-14-correct-fragment-from-case-and-application",
                    fixture("hearing-results-from-case-and-application.json"),
                    "2021-03-11T22:18:24.506Z");
        }

        @Test
        @DisplayName("should filter unique prosecutionAuthId")
        void should_filter_unique_authority_across_case_and_application() {
            assertParity(
                    "case-15-mixed-filter-unique-authority",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"))
                            + "," + applications(
                            application("prosecution-auth-id-2", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter unique prosecutionAuthId but not master defendant id")
        void should_filter_unique_authority_but_not_master_defendant_across_both() {
            assertParity(
                    "case-16-mixed-unique-authority-not-master-defendant",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"))
                            + "," + applications(
                            application("prosecution-auth-id-2", "master-defendant-id-1"))),
                    null);
        }

        @Test
        @DisplayName("should group fragments by prosecutionAuthId from both case and application")
        void should_group_fragments_by_authority_across_both() {
            assertParity(
                    "case-17-mixed-group-by-authority",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"))
                            + "," + applications(
                            application("prosecution-auth-id-1", "master-defendant-id-2"))),
                    null);
        }

        @Test
        @DisplayName("should filter by prosecution authority id and then by master defendant id")
        void should_filter_by_authority_then_master_defendant_across_both() {
            assertParity(
                    "case-18-mixed-filter-authority-then-master-defendant",
                    hearing(cases(prosecutionCase("prosecution-auth-id-1", "master-defendant-id-1"))
                            + "," + applications(
                            application("prosecution-auth-id-1", "master-defendant-id-1"))),
                    null);
        }
    }

    @Nested
    @DisplayName("Set Informant Register from court application without master defendant and case")
    class FromCaseAndApplicationWithoutMasterDefendant {

        @Test
        @DisplayName("should return the correct fragment from case and application without master")
        void should_return_the_correct_fragment_from_case_and_application_without_master() {
            assertParity(
                    "case-19-case-and-application-without-master-defendant",
                    fixture(
                        "hearing-results-from-case-and-application-without-master-defandant.json"),
                    "2021-03-11T22:18:24.506Z");
        }
    }

    /**
     * Runs one twin: build the fragments, then hold the whole tree to the golden.
     *
     * @param caseName   the golden file to compare against
     * @param hearing    the hearing tree to transform
     * @param sharedTime the shared time, or {@code null} where the Jest case passes none
     */
    private void assertParity(
            final String caseName, final JsonNode hearing, final String sharedTime) {

        final List<RegisterFragment> fragments = builder.build(hearing, sharedTime);
        final JsonNode expected = golden(caseName);

        if (expected.isObject() && expected.has("undefined")) {
            assertThat(fragments)
                    .as("%s — the legacy produces no fragments at all for this hearing", caseName)
                    .isEmpty();
            return;
        }

        JsonParity.assertMatches(expected, mapper.valueToTree(fragments), caseName);
    }

    /**
     * Loads a golden captured from the legacy function app.
     *
     * @param caseName the case name
     * @return the golden tree
     */
    private JsonNode golden(final String caseName) {
        return read(FIXTURES + "expected/" + caseName + ".json");
    }

    /**
     * Loads one of the byte-identical Jest fixtures.
     *
     * @param name the fixture file name
     * @return the hearing tree
     */
    private JsonNode fixture(final String name) {
        return read(FIXTURES + name);
    }

    /**
     * Reads a JSON resource from the test classpath.
     *
     * @param resource the absolute classpath location
     * @return the parsed tree
     */
    private JsonNode read(final String resource) {
        try (InputStream stream = getClass().getResourceAsStream(resource)) {
            if (stream == null) {
                throw new IllegalStateException("missing test resource " + resource);
            }
            return mapper.readTree(new String(stream.readAllBytes(), StandardCharsets.UTF_8));
        } catch (java.io.IOException cannotRead) {
            throw new IllegalStateException("could not read " + resource, cannotRead);
        }
    }

    /**
     * Builds one of the inline hearings the Jest suite declares, transcribed from the source.
     *
     * <p>The court centre is not decoration: the legacy vocabulary step reads
     * {@code courtCentre.welshCourtCentre} without a guard, so every inline Jest hearing carries one
     * and a hearing without one produces nothing at all.
     *
     * @param members the {@code prosecutionCases} and/or {@code courtApplications} members
     * @return the hearing tree
     */
    private JsonNode hearing(final String members) {
        return mapper.readTree("{" + members + ","
                + "\"courtCentre\":{"
                + "\"id\":\"6647df67-a065-4d07-90ba-a8daa064ecd9\","
                + "\"name\":\"Lavender Hill\"}}");
    }

    /**
     * Wraps prosecution cases as the hearing's {@code prosecutionCases} member.
     *
     * @param cases the case objects
     * @return the member text
     */
    private static String cases(final String... cases) {
        return "\"prosecutionCases\":[" + String.join(",", cases) + "]";
    }

    /**
     * Wraps court applications as the hearing's {@code courtApplications} member.
     *
     * @param applications the application objects
     * @return the member text
     */
    private static String applications(final String... applications) {
        return "\"courtApplications\":[" + String.join(",", applications) + "]";
    }

    /**
     * One inline prosecution case with a single defendant and no results.
     *
     * @param authorityId       the prosecuting authority
     * @param masterDefendantId the defendant's identity
     * @return the case object text
     */
    private static String prosecutionCase(
            final String authorityId, final String masterDefendantId) {
        return "{\"prosecutionCaseIdentifier\":{\"prosecutionAuthorityId\":\""
                + authorityId + "\"},"
                + "\"defendants\":[{\"masterDefendantId\":\"" + masterDefendantId + "\","
                + "\"defendantCaseJudicialResults\":[],\"offences\":[]}]}";
    }

    /**
     * One inline court application with a prosecuting applicant and a master defendant subject.
     *
     * @param authorityId       the prosecuting authority
     * @param masterDefendantId the subject's identity
     * @return the application object text
     */
    private static String application(
            final String authorityId, final String masterDefendantId) {
        return "{\"applicant\":{\"prosecutingAuthority\":{\"prosecutionAuthorityId\":\""
                + authorityId + "\"}},"
                + "\"subject\":{\"masterDefendant\":{\"masterDefendantId\":\""
                + masterDefendantId + "\"}}}";
    }
}
