gatling {
  core {
    encoding = "utf-8"
    shutdownTimeout = 5000
    elFileBodiesCacheMaxCapacity = 200
  }
  jms {
    replyTimeoutScanPeriod = 1000
  }
  data {
    writers = [console, file]
    console {
      light = false
      writePeriod = 5
    }
  }
}
