package uk.gov.hmcts.cp.simulation;

import java.time.LocalDate;
import java.util.UUID;

/**
 * One {@code DistributionCommand} as generated by {@link MessageBuilder}, with the identifiers the
 * output verifier correlates on.
 *
 * <p>{@code hearingId} is the correlation key: the WireMock hearing-payload stub echoes it back as
 * {@code hearing.id}, so every Results POST the service makes for this message carries it in its
 * body. A duplicate is the same instance republished — same requestId, same hearingId — and must
 * produce no additional POSTs.
 *
 * @param requestId the message's requestId (the service's idempotency key with {@code source})
 * @param hearingId the message's hearingId (the verifier's correlation key)
 * @param hearingDay the day used in the Redis claim-check key
 * @param body      the exact JSON published to the queue
 */
public record PublishedMessage(UUID requestId, UUID hearingId, LocalDate hearingDay, String body) {
}
